/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see pub https:///platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec pub version: 2.3.0
 *
 * Generated pub by: https:///github.com/swagger-api/swagger-codegen.git
 */

/// # on openapi.yaml
///
/// ```yaml
/// ChatCompletionRequestMessageContentPartRefusal:
///   type: object
///   title: Refusal content part
///   properties:
///     type:
///       type: string
///       enum:
///         - refusal
///       description: The type of the content part.
///       x-stainless-const: true
///     refusal:
///       type: string
///       description: The refusal message generated by the model.
///   required:
///     - type
///     - refusal
/// ```
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct ChatCompletionRequestMessageContentPartRefusal {
    /// The refusal message generated by the model.
    #[serde(rename = "refusal")]
    pub refusal: String,
    /// The type of the content part.
    #[serde(rename = "type")]
    pub _type: String,
}
