/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see pub https:///platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec pub version: 2.3.0
 *
 * Generated pub by: https:///github.com/swagger-api/swagger-codegen.git
 */

use crate::ChatCompletionMessageToolCall;

/// # on openapi.yaml
///
/// ```yaml
/// ChatCompletionMessageToolCalls:
///   type: array
///   description: The tool calls generated by the model, such as function calls.
///   items:
///     $ref: "#/components/schemas/ChatCompletionMessageToolCall"
/// ```
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionMessageToolCalls(Vec<ChatCompletionMessageToolCall>);
