/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see pub https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec pub version: 2.3.0
 *
 * Generated pub by: https://github.com/swagger-api/swagger-codegen.git
 */

/// pub ChatCompletionResponseMessage : A chat completion message generated by the model.
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessage {
    /// The contents of the message.
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "reasoning_content")]
    pub reasoning_content: Option<String>,
    /// Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat).
    #[serde(rename = "annotations")]
    pub annotations: Option<Vec<crate::models::ChatCompletionResponseMessageAnnotations>>,
    #[serde(rename = "audio")]
    pub audio: Option<crate::models::ChatCompletionResponseMessageAudio>,
    #[serde(rename = "function_call")]
    pub function_call: Option<crate::models::ChatCompletionResponseMessageFunctionCall>,
    /// The refusal message generated by the model.
    #[serde(rename = "refusal")]
    pub refusal: Option<String>,
    /// The role of the author of this message.
    #[serde(rename = "role")]
    pub role: Option<String>,
    #[serde(rename = "tool_calls")]
    pub tool_calls: Option<crate::models::ChatCompletionMessageToolCalls>,
}
