/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see pub https:///platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec pub version: 2.3.0
 *
 * Generated pub by: https:///github.com/swagger-api/swagger-codegen.git
 */

/// # on openapi.yaml
///
/// ```yaml
/// ChatCompletionMessageToolCallChunk:
///   type: object
///   properties:
///     index:
///       type: integer
///     id:
///       type: string
///       description: The ID of the tool call.
///     type:
///       type: string
///       enum:
///         - function
///       description: The type of the tool. Currently, only `function` is supported.
///       x-stainless-const: true
///     function:
///       type: object
///       properties:
///         name:
///           type: string
///           description: The name of the function to call.
///         arguments:
///           type: string
///           description:
///             The arguments to call the function with, as generated by the model
///             in JSON format. Note that the model does not always generate
///             valid JSON, and may hallucinate parameters not defined by your
///             function schema. Validate the arguments in your code before
///             calling your function.
///   required:
///     - index
/// ```
#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionMessageToolCallChunk {
    #[serde(rename = "function")]
    pub function: Option<crate::models::ChatCompletionMessageToolCallChunkFunction>,
    /// The ID of the tool call.
    #[serde(rename = "id")]
    pub id: Option<String>,
    #[serde(rename = "index")]
    pub index: i32,
    /// The type of the tool. Currently, only `function` is supported.
    #[serde(rename = "type")]
    pub _type: Option<String>,
}
