/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see pub https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec pub version: 2.3.0
 *
 * Generated pub by: https://github.com/swagger-api/swagger-codegen.git
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessageAudio {
    /// Base64 encoded audio bytes generated by the model, in the format specified in the request.
    #[serde(rename = "data")]
    pub data: String,
    /// The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the server for use in multi-turn conversations.
    #[serde(rename = "expires_at")]
    pub expires_at: i32,
    /// Unique identifier for this audio response.
    #[serde(rename = "id")]
    pub id: String,
    /// Transcript of the audio generated by the model.
    #[serde(rename = "transcript")]
    pub transcript: String,
}
