/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see pub https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec pub version: 2.3.0
 *
 * Generated pub by: https://github.com/swagger-api/swagger-codegen.git
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct CompletionUsageCompletionTokensDetails {
    /// When using Predicted Outputs, the number of tokens in the prediction that appeared in the completion.
    #[serde(rename = "accepted_prediction_tokens")]
    pub accepted_prediction_tokens: Option<i32>,
    /// Audio input tokens generated by the model.
    #[serde(rename = "audio_tokens")]
    pub audio_tokens: Option<i32>,
    /// Tokens generated by the model for reasoning.
    #[serde(rename = "reasoning_tokens")]
    pub reasoning_tokens: Option<i32>,
    /// When using Predicted Outputs, the number of tokens in the prediction that did not appear in the completion. However, like reasoning tokens, these tokens are still counted in the total completion tokens for purposes of billing, output, and context window limits.
    #[serde(rename = "rejected_prediction_tokens")]
    pub rejected_prediction_tokens: Option<i32>,
}
