/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see pub https:///platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec pub version: 2.3.0
 *
 * Generated pub by: https:///github.com/swagger-api/swagger-codegen.git
 */

/// # on openapi.yaml
///
/// ```yaml
/// CreateEmbeddingResponse:
///   type: object
///   properties:
///     data:
///       type: array
///       description: The list of embeddings generated by the model.
///       items:
///         $ref: "#/components/schemas/Embedding"
///     model:
///       type: string
///       description: The name of the model used to generate the embedding.
///     object:
///       type: string
///       description: The object type, which is always "list".
///       enum:
///         - list
///       x-stainless-const: true
///     usage:
///       type: object
///       description: The usage information for the request.
///       properties:
///         prompt_tokens:
///           type: integer
///           description: The number of tokens used by the prompt.
///         total_tokens:
///           type: integer
///           description: The total number of tokens used by the request.
///       required:
///         - prompt_tokens
///         - total_tokens
///   required:
///     - object
///     - model
///     - data
///     - usage
/// ```
#[derive(Debug, Serialize, Deserialize)]
pub struct CreateEmbeddingResponse {
    /// The list of embeddings generated by the model.
    #[serde(rename = "data")]
    pub data: Vec<crate::models::Embedding>,
    /// The name of the model used to generate the embedding.
    #[serde(rename = "model")]
    pub model: String,
    /// The object type, which is always \"list\".
    #[serde(rename = "object")]
    pub object: String,
    #[serde(rename = "usage")]
    pub usage: crate::models::CreateEmbeddingResponseUsage,
}
