/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see pub https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec pub version: 2.3.0
 *
 * Generated pub by: https://github.com/swagger-api/swagger-codegen.git
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct FunctionToolCall {
    /// A JSON string of the arguments to pass to the function.
    #[serde(rename = "arguments")]
    pub arguments: String,
    /// The unique ID of the function tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The unique ID of the function tool call.
    #[serde(rename = "id")]
    pub id: Option<String>,
    /// The name of the function to run.
    #[serde(rename = "name")]
    pub name: String,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    #[serde(rename = "status")]
    pub status: Option<String>,
    /// The type of the function tool call. Always `function_call`.
    #[serde(rename = "type")]
    pub _type: String,
}
