/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see pub https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec pub version: 2.3.0
 *
 * Generated pub by: https://github.com/swagger-api/swagger-codegen.git
 */

/// pub FunctionCallOutputItemParam : The output of a function tool call.
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FunctionCallOutputItemParam {
    /// The unique ID of the function tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    #[serde(rename = "id")]
    pub id: Option<Value>,
    /// A JSON string of the output of the function tool call.
    #[serde(rename = "output")]
    pub output: String,
    #[serde(rename = "status")]
    pub status: Option<Value>,
    /// The type of the function tool call output. Always `function_call_output`.
    #[serde(rename = "type")]
    pub _type: String,
}
