/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see pub https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec pub version: 2.3.0
 *
 * Generated pub by: https://github.com/swagger-api/swagger-codegen.git
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct FunctionToolCallOutputResource {
    /// The unique ID of the function tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The unique ID of the function call tool output.
    #[serde(rename = "id")]
    pub id: String,
    /// A JSON string of the output of the function tool call.
    #[serde(rename = "output")]
    pub output: String,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    #[serde(rename = "status")]
    pub status: Option<String>,
    /// The type of the function tool call output. Always `function_call_output`.
    #[serde(rename = "type")]
    pub _type: String,
}
